version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: politiks-postgres
    environment:
      POSTGRES_USER: politiks
      POSTGRES_PASSWORD: politiks
      POSTGRES_DB: politiks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U politiks"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - politiks-network

volumes:
  postgres_data:

networks:
  politiks-network:
    driver: bridge
